automatic mapping of table names to extractors
calgo-lab/green-db pull request #41
Opened 2022-03-07 13:23 UTC by en-GB

removes some manual steps to adding new shops

2022-03-09 09:08 UTC, se-jaeger reviewed
In the future, short description of the PR would be nice.

To be honest, I don't see the benefit here. If this mapping is split and moved to separate files and then created dynamically, IMHO it makes things worse than have a single and static mapping.

Is it possible to "find" these functions (I think it's also fine to expect that this function exists), e.g., `extract_otto` in the file `otto` dynamically and directly return the mapping instead of return the `names`?

2022-03-09 09:08 UTC, se-jaeger commented on extract/extract/extractors/otto.py
> +EXTRACTOR_FOR_TABLE_NAME = {TABLE_NAME_SCRAPING_OTTO: extract_otto}
We still need these mappings?

2022-03-09 09:08 UTC, se-jaeger commented on extract/extract/extractors/zalando.py
> +EXTRACTOR_FOR_TABLE_NAME = {TABLE_NAME_SCRAPING_ZALANDO: extract_zalando}
See above..

2022-03-09 16:20 UTC, en-GB commented on extract/extract/extractors/__init__.py
> +from . import *
it seems to be.
i dont know that much about python modules so im sure there is a better way to do this

2022-03-10 08:50 UTC, se-jaeger commented
I pushed a suggestions. It does not need any indirections or decorators and has much fewer lines of code.
It just relies on file names, e.g., `otto.py` or `zalando.py` used as table names and they need to expose the function `extract` (no suffix). WDYT?

2022-03-10 15:40 UTC, en-GB commented
by indirection you mean the `import *` in `extractors/__init__.py`?
i still feel like thats better than using `import_module`

2022-03-14 09:04 UTC, se-jaeger requested changes
I would prefer to be as explicit as possible. Using `import *` imports things we do not know about. If possible, let avoid it.

2022-03-14 09:04 UTC, se-jaeger commented on extract/extract/extractors/__init__.py
> +# for some reason it only finds them when __all__ is set
Can we construct `EXTRACTOR_FOR_TABLE_NAME` in this file?

2022-03-14 09:04 UTC, se-jaeger commented on extract/extract/__init__.py
> +from . import extractors
And then import it here: `from .extractors import EXTRACTOR_FOR_TABLE_NAME`?

2022-03-14 14:06 UTC, en-GB commented
closed as discussed

2022-03-14 14:06 UTC, closed without merging