add otto EU_ENERGY_LABEL extraction for electronics
calgo-lab/green-db pull request #71
Opened 2022-05-31 16:58 UTC by BigDatalex

This PR adds functionality to extract the (new) `EU_ENERGY_LABEL` for otto electronics categories. So far we have used just the private otto label `energieefiziente Nutzung` which was mapped to `OTHER`.

I implemented this in a seperate method and added also a separate `_LABEL_MAPPING_ENERGY` because the mapping relies just on one character, which identifies the level of the label e.g. `C` for `EU_ENERGY_LABEL_C` and this could lead to problems if the mapping would be combined with the original `_LABEL_MAPPING`.

2022-06-13 11:13 UTC, se-jaeger requested changes
Thanks for this PR!

@AdriaSG and @wkrl  came up with this very nice utils function: https://github.com/calgo-lab/green-db/blob/main/extract/extract/utils.py#L28

It first checks all available certificates and, secondly, tries a shop specific `_LABEL_MAPPING`. This helps to reduce duplicated mapping definitions and in general streamlines the extraction.

Would be nice if you could use this function now. This would require to remove the unnecessary entries of `_LABEL_MAPPING` (e.g. `GOTS organic`) and combine it with `_LABEL_MAPPING_ENERGY`.

2022-06-15 08:22 UTC, se-jaeger submitted a review, later dismissed
👍🏼

2022-06-15 08:57 UTC, BigDatalex reviewed
I would not remove this mapping, because there are electronics, which do not have the `EU ENERGY LABEL` und this would result now in a lot of `UNKNOWN` certificates, instead of `OTHER`.

2022-06-15 10:41 UTC, se-jaeger commented
> @se-jaeger I would not remove this mapping, because there are electronics, which do not have the `EU ENERGY LABEL` und this would result now in a lot of `UNKNOWN` certificates, instead of `OTHER`.

That's a good point. Will revert it 👍🏼

2022-06-15 10:42 UTC, se-jaeger approved these changes

2022-06-15 11:01 UTC, merged